@CENTOS_6_INC@

ENV CJOSE_VERSION @CJOSE_VERSION@
ENV CJOSE_PKG cjose-${CJOSE_VERSION}-1.el6.x86_64.rpm
@CENTOS_INSTALL_CJOSE@

RUN curl -o hiredis-0.12.1-1.sdl6.x86_64.rpm http://springdale.math.ias.edu/data/puias/unsupported/6/x86_64/hiredis-0.12.1-1.sdl6.x86_64.rpm
RUN yum localinstall -y hiredis-0.12.1-1.sdl6.x86_64.rpm

ENV MOD_AUTH_OPENIDC_VERSION @MOD_AUTH_OPENIDC_VERSION@
ENV MOD_AUTH_OPENIDC_PKG mod_auth_openidc-${MOD_AUTH_OPENIDC_VERSION}-1.el6.x86_64.rpm
@CENTOS_INSTALL_MOD_AUTH_OPENIDC@

ADD 000-default.conf /etc/httpd/conf.d/
RUN service httpd start && curl -v http://localhost/protected/index.php 2>&1 | grep "Location:" | grep "accounts.google.com/o/oauth2/auth"
