@CENTOS_6_INC@

ENV MOD_AUTH_OPENIDC_VERSION @MOD_AUTH_OPENIDC_VERSION@
ENV CJOSE_VERSION @CJOSE_VERSION@

ENV CJOSE_PKG cjose-${CJOSE_VERSION}-1.el6.x86_64.rpm
@CENTOS_INSTALL_CJOSE@

ENV MOD_AUTH_OPENIDC_PKG mod_auth_openidc-${MOD_AUTH_OPENIDC_VERSION}-1.el6.x86_64.rpm
@CENTOS_INSTALL_MOD_AUTH_OPENIDC@

ADD 000-default.conf /etc/httpd/conf.d/
RUN service httpd start && curl -v http://localhost/protected/index.php 2>&1 | grep "Location:" | grep "accounts.google.com/o/oauth2/auth"
