FROM ubuntu:precise
MAINTAINER hans.zandbelt@zmartzone.eu

# Ubuntu 12.04 LTS

RUN apt-get clean && apt-get --fix-missing update
RUN apt-get update && apt-get install -y apt-utils curl

ENV CJOSE_VERSION @CJOSE_VERSION@
ENV CJOSE_PKG libcjose_${CJOSE_VERSION}-1~bpo70+1_amd64.deb
@DEBIAN_INSTALL_CJOSE@

RUN apt-get update && apt-get install -y libhiredis0.10
ENV MOD_AUTH_OPENIDC_VERSION @MOD_AUTH_OPENIDC_VERSION@
ENV MOD_AUTH_OPENIDC_PKG libapache2-mod-auth-openidc_${MOD_AUTH_OPENIDC_VERSION}-1~bpo70+1_amd64.deb
@DEBIAN_INSTALL_MOD_AUTH_OPENIDC@

ADD default /etc/apache2/sites-available/
RUN a2enmod auth_openidc
RUN service apache2 start && curl -v http://localhost/protected/index.php 2>&1 | grep "Location:" | grep "accounts.google.com/o/oauth2/auth"
