FROM ubuntu:yakkety
MAINTAINER hans.zandbelt@zmartzone.eu

# Ubuntu 16.10

RUN apt-get clean && apt-get --fix-missing update
RUN apt-get update && apt-get install -y apt-utils curl

ENV CJOSE_VERSION @CJOSE_VERSION@
ENV CJOSE_PKG libcjose0_${CJOSE_VERSION}-1~wily+1_amd64.deb
@DEBIAN_INSTALL_CJOSE@

RUN apt-get update && apt-get install -y debian-keyring debian-archive-keyring
RUN echo "deb http://ftp.debian.org/debian stretch main" > /etc/apt/sources.list.d/stretch.list
RUN apt-get update && apt-get -t stretch install -y libjq1
RUN mv /etc/apt/sources.list.d/stretch.list /etc/apt/sources.list.d/stretch.list.backup

RUN apt-get update && apt-get install -y libhiredis0.13 libcurl3
ENV MOD_AUTH_OPENIDC_VERSION @MOD_AUTH_OPENIDC_VERSION@
ENV MOD_AUTH_OPENIDC_PKG libapache2-mod-auth-openidc_${MOD_AUTH_OPENIDC_VERSION}-1~wily+1_amd64.deb
@DEBIAN_INSTALL_MOD_AUTH_OPENIDC@

ADD 000-default.conf /etc/apache2/sites-available/
RUN a2enmod auth_openidc
RUN service apache2 start && curl -v http://localhost/protected/index.php 2>&1 | grep "Location:" | grep "accounts.google.com/o/oauth2/auth"
